# Generated by Django 5.2.3 on 2025-07-19 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_taskdetail_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetail',
            name='asset',
            field=models.ImageField(blank=True, default='task_asset/default.png', null=True, upload_to='task_asset'),
        ),
    ]
